### ISSUE TITLE
Confusing Windows-only information for vCenter

### ISSUE THREAD

**Issue by scaleoutsean** [NetAppDocs/e-series#69]
Page: [Review installation and upgrade requirements](https://docs.netapp.com/us-en/e-series/vcenter-plugin/san-spvc-ic-reqs.html)

> Supported application host versions: Windows 2016, Windows 2019, Windows 2022

> You can install only one instance of Storage Plugin for vCenter on a Windows host and can only register it to one vCSA.

It seems there are many references to Windows. It hasn't been supported as OS host for vCenter since 6.7U3. 

https://kb.vmware.com/s/article/2091273

At the same time information about Photon OS (vCenter host OS in recent years) is absent.

It's better to remove this stuff about Windows, or it there's value to it and reason for it being there, add Photon OS information as well.

**Comment by brookwilson** [comment]
You are getting confused between the vCenter Server Applicance (vCSA) and the Storage plugin for vCenter application that NetApp developed. The requirements listed in the documentation is referring to the Storage plugin for vCenter and not requirements for vCSA, VMware takes care of that. So when the customer installs the Storage plugin for vCenter on a windows host we like to reference the host as an application host, so the supported application host for the Storage plugin for vCenter will be either Windows 2016, Windows 2019, and Windows 2022. Once the plugin is installed on the supported Windows application host then you are required to register the plugin to only one vCSA. The supporting vCSA for the plugin will be 6.7U3J, 7.0U1, 7.0U2, 7.0U3, and 8.0. The application host can be either a physical machine or a VM. If you decide to use a VM then VMware's Guest OS compatibility guide states the Windows versions supported by the plugin are still supported by VMware. There is no need to have Photon OS information in the plugin documentation because the VMware Photon OS is used for the vCSA.
[VMware_GOS_Compatibility_Guide.pdf](https://github.com/NetAppDocs/e-series/files/10448416/VMware_GOS_Compatibility_Guide.pdf)

**Comment by netapp-jsnyder** [comment]
@brookwilson thanks for clarifying. @scaleoutsean do you have any additional questions? Can I close this issue?

**Comment by scaleoutsean** [comment]
Yes, it does make sense, thank you!
